import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import weatherRoutes from './routes/weatherRoutes';
import { errorHandler } from './middleware/errorHandler';
const app = express();
const PORT = process.env.PORT || 5000;
app.use(cors()); app.use(express.json());
app.get('/api/health', (_req, res) => res.json({ status: 'ok', message: 'WeatherGuard backend is running' }));
app.use('/api/weather', weatherRoutes);
app.use(errorHandler);
app.listen(Number(PORT), '0.0.0.0', () => console.log(`WeatherGuard backend listening on port ${PORT}`));
